/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-125515-g35f8f4bdc0-20260710"
#endif /* AVUTIL_FFVERSION_H */
