export const featuresIntro = {
  eyebrow: 'Platform Features',
  pageTitle: 'Everything your team needs to build, brand, and publish',
  pageLead:
    'From loaders and fonts to templates, color theming, and generative AI — explore every capability of the Proxwebs CMS in one place.',
};

/**
 * Each feature:
 * - slug: detail route
 * - demo: FeatureDemo scene key
 * - points: shown on card (first 5) + full list on detail
 * - highlights: detail-page callouts
 * - steps: how-it-works on detail
 */
export const features = [
  {
    id: 'loaders',
    slug: 'multiple-loaders',
    title: 'Multiple Loaders',
    summary: 'Pick the loading animation that matches your brand personality.',
    demo: 'loaders',
    image: 'feature-loaders.jpg',
    accent: '#03a4ed',
    points: [
      'Choose from a library of ready-made loader styles',
      'Preview loaders before applying them site-wide',
      'Match loader motion to your brand tone',
      'Swap loaders anytime without code changes',
      'Keep first-load experience polished and on-brand',
      'Apply different loaders per template when needed',
      'Lightweight animations that stay performance-friendly',
    ],
    body: 'First impressions start before the page finishes loading. Proxwebs lets you select from multiple loader styles so every visit feels intentional — whether you want a calm pulse, a modern spinner, or a branded motion cue.',
    highlights: [
      { title: 'Visual picker', text: 'Browse loaders in the admin and apply with one click.' },
      { title: 'Brand fit', text: 'Choose motion that feels premium, playful, or minimal.' },
      { title: 'No deploy needed', text: 'Change loaders instantly from the dashboard.' },
    ],
    steps: [
      { title: 'Open loaders', text: 'Go to design settings and open the loader gallery.' },
      { title: 'Preview', text: 'Watch each animation play before you commit.' },
      { title: 'Apply', text: 'Select a loader and publish — it goes live immediately.' },
    ],
  },
  {
    id: 'fonts',
    slug: 'google-fonts',
    title: 'Font Library',
    summary: 'Select Google Fonts that make your site feel unmistakably yours.',
    demo: 'fonts',
    image: 'feature-fonts.jpg',
    accent: '#ff695f',
    points: [
      'Browse and apply Google Fonts from the dashboard',
      'Set heading and body typefaces independently',
      'Preview typography on real page layouts',
      'Keep brand consistency across every template',
      'Update fonts globally without touching code',
      'Pair fonts for contrast and readability',
      'Ship typography changes in real time',
    ],
    body: 'Typography is half of your brand. Choose fonts that fit your voice, preview them on live layouts, and roll them out across the whole site — headings, body copy, and UI text — without a developer ticket.',
    highlights: [
      { title: 'Google Fonts ready', text: 'Access a curated set of web-safe brand fonts.' },
      { title: 'Global control', text: 'One change updates the entire website look.' },
      { title: 'Live preview', text: 'See type choices on real sections before publishing.' },
    ],
    steps: [
      { title: 'Pick fonts', text: 'Select heading and body fonts from the library.' },
      { title: 'Preview', text: 'Check readability and hierarchy on sample pages.' },
      { title: 'Publish', text: 'Apply site-wide and go live instantly.' },
    ],
  },
  {
    id: 'website-templates',
    slug: 'website-templates',
    title: 'Website Templates',
    summary: 'Switch the entire look — navbar, footer, and sections — in minutes.',
    demo: 'templates',
    image: 'feature-templates.jpg',
    accent: '#03a4ed',
    points: [
      'Ready-made website templates for fast restyling',
      'Each template includes navbar and footer styling',
      'Live preview before you apply a look',
      'Swap templates without rebuilding pages',
      'Keep content while changing the visual system',
      'Ideal for seasonal campaigns and rebrands',
      'Consistent spacing, cards, and section rhythm',
    ],
    body: 'Start from polished website templates instead of a blank canvas. Preview a look, apply it, and keep your content intact while the visual system — including navigation and footer — updates around it.',
    highlights: [
      { title: 'Full-site themes', text: 'Templates restyle more than a single page.' },
      { title: 'Safe preview', text: 'Evaluate the look before committing.' },
      { title: 'Content preserved', text: 'Swap design without rewriting your pages.' },
    ],
    steps: [
      { title: 'Browse templates', text: 'Open the template gallery in the admin.' },
      { title: 'Live preview', text: 'See how your content looks in each theme.' },
      { title: 'Apply', text: 'One click restyles the site end to end.' },
    ],
  },
  {
    id: 'login-templates',
    slug: 'login-templates',
    title: 'Login Templates',
    summary: 'Give admins and users a branded, polished sign-in experience.',
    demo: 'login',
    image: 'feature-login.jpg',
    accent: '#ff695f',
    points: [
      'Multiple login screen layouts to choose from',
      'Brand-aligned sign-in pages out of the box',
      'Preview login templates before applying',
      'Keep authentication looking as good as the site',
      'Swap login designs without custom CSS',
      'Support for clean, modern, and bold styles',
      'Consistent with your selected website template',
    ],
    body: 'Your login screen is part of the product. Choose from multiple login templates so staff and stakeholders land on a branded, trustworthy authentication experience that matches the rest of the site.',
    highlights: [
      { title: 'Template gallery', text: 'Pick from several ready login layouts.' },
      { title: 'Brand continuity', text: 'Align sign-in with your public website look.' },
      { title: 'Instant switch', text: 'Change login design without engineering work.' },
    ],
    steps: [
      { title: 'Open login templates', text: 'Browse available authentication layouts.' },
      { title: 'Preview', text: 'Check desktop and mobile sign-in presentation.' },
      { title: 'Activate', text: 'Apply the template and publish.' },
    ],
  },
  {
    id: 'template-colors',
    slug: 'template-colors',
    title: 'Template Color Customization',
    summary: 'Tune primary, accent, and surface colors until the template feels on-brand.',
    demo: 'colors',
    image: 'feature-colors.jpg',
    accent: '#03a4ed',
    points: [
      'Customize website template colors visually',
      'Adjust primary, accent, and supporting tones',
      'See color changes update in live preview',
      'Keep contrast readable across sections',
      'Save brand palettes for consistent reuse',
      'Restyle buttons, links, and highlights together',
      'No CSS files required for everyday theming',
    ],
    body: 'Templates get you 80% there — color customization finishes the job. Dial in brand blues, coral accents, and surface tones so every button, link, and highlight feels like your company, not a stock theme.',
    highlights: [
      { title: 'Visual color controls', text: 'Change palette values from the dashboard.' },
      { title: 'Live feedback', text: 'Watch the template respond as you adjust.' },
      { title: 'Brand-safe defaults', text: 'Start from balanced palettes, then refine.' },
    ],
    steps: [
      { title: 'Select a template', text: 'Start from a website template you like.' },
      { title: 'Tune colors', text: 'Adjust primary and accent colors visually.' },
      { title: 'Publish palette', text: 'Save and roll the look out site-wide.' },
    ],
  },
  {
    id: 'generative-ai',
    slug: 'generative-ai',
    title: 'Generative AI Content & Images',
    summary: 'Zelo helps you draft copy and create visuals without leaving the CMS.',
    demo: 'ai',
    image: 'feature-ai.jpg',
    accent: '#ff695f',
    points: [
      'Generate headlines, body copy, and CTAs from prompts',
      'Enhance, rewrite, shorten, or expand existing text',
      'Create images tailored to each section',
      'Auto-fit generated and uploaded images to slots',
      'SEO-friendly titles, taglines, and descriptions',
      'Chat and voice assistance while you edit',
      'Permissions keep AI-assisted publishing safe',
    ],
    body: 'Blank-page friction disappears when AI lives inside the workflow. Describe what you need, generate copy and images, refine the tone, and publish — all without bouncing between separate tools.',
    highlights: [
      { title: 'Prompt to publish', text: 'Draft content where the page is built.' },
      { title: 'Image generation', text: 'Create and fit visuals for each layout slot.' },
      { title: 'Brand guardrails', text: 'Edit, approve, and publish with role controls.' },
    ],
    steps: [
      { title: 'Describe', text: 'Tell Zelo what the section should say and show.' },
      { title: 'Generate', text: 'Produce copy and images tailored to the layout.' },
      { title: 'Refine & publish', text: 'Polish tone, preview, and go live.' },
    ],
  },
  {
    id: 'visual-builder',
    slug: 'visual-page-builder',
    title: 'Visual Page Builder',
    summary: 'Assemble pages from sections — no code, no deploy pipeline for everyday edits.',
    demo: 'builder',
    image: 'feature-builder.jpg',
    accent: '#03a4ed',
    points: [
      'Create and reorder pages visually',
      'Edit section content in place',
      'Build layouts from reusable blocks',
      'Preview changes before publishing',
      'Empower marketing to own day-to-day updates',
      'Reduce developer tickets for routine content work',
      'Keep structure consistent across the site',
    ],
    body: 'The visual page builder turns website updates into a dashboard task. Staff create pages, rearrange sections, and edit content in context — so campaigns ship while developers stay focused on product work.',
    highlights: [
      { title: 'No-code editing', text: 'Non-technical teams can own the website.' },
      { title: 'Section-based layout', text: 'Compose pages from modular building blocks.' },
      { title: 'Faster turnaround', text: 'Ship seasonal and campaign pages quickly.' },
    ],
    steps: [
      { title: 'Create a page', text: 'Add a page and choose a starting structure.' },
      { title: 'Arrange sections', text: 'Reorder blocks until the story flows.' },
      { title: 'Edit & publish', text: 'Update copy and go live in real time.' },
    ],
  },
  {
    id: 'menus',
    slug: 'menu-management',
    title: 'Menu Management',
    summary: 'Build and update navigation from the admin — no template digging.',
    demo: 'menus',
    image: 'feature-menus.jpg',
    accent: '#ff695f',
    points: [
      'Create and reorder navigation items visually',
      'Keep header menus aligned with site structure',
      'Update links when pages change',
      'Support clear information architecture',
      'Publish menu changes instantly',
      'Reduce broken-link risk during restructures',
      'Give ops teams control without code access',
    ],
    body: 'Navigation should evolve with your content. Manage menus from the same dashboard as pages so structure stays clear, links stay accurate, and visitors always find what they need.',
    highlights: [
      { title: 'Visual menu editor', text: 'Drag and organize links without code.' },
      { title: 'Structure sync', text: 'Keep nav aligned as pages grow.' },
      { title: 'Instant updates', text: 'Menu changes publish in real time.' },
    ],
    steps: [
      { title: 'Open menus', text: 'Edit navigation from the admin dashboard.' },
      { title: 'Organize links', text: 'Add, rename, and reorder items.' },
      { title: 'Publish', text: 'Push the updated menu live immediately.' },
    ],
  },
  {
    id: 'sections',
    slug: 'reusable-sections',
    title: 'Reusable Sections',
    summary: 'Build once, reuse everywhere — consistent layouts at campaign speed.',
    demo: 'sections',
    image: 'feature-sections.jpg',
    accent: '#03a4ed',
    points: [
      'Maintain a library of reusable section blocks',
      'Drop proven layouts into new pages',
      'Reorder sections to reshape a page quickly',
      'Keep design consistency across campaigns',
      'Reduce one-off layout sprawl',
      'Pair sections with AI-generated content',
      'Scale page production without redesigning each time',
    ],
    body: 'Reusable sections are the difference between rebuilding and remixing. Save strong layouts, drop them into new pages, and fill them with fresh content — so every campaign starts ahead.',
    highlights: [
      { title: 'Section library', text: 'Reuse hero, feature, CTA, and content blocks.' },
      { title: 'Fast remixing', text: 'Reorder blocks instead of redesigning.' },
      { title: 'Consistent UX', text: 'Keep spacing and hierarchy on-brand.' },
    ],
    steps: [
      { title: 'Pick a section', text: 'Choose a block from the reusable library.' },
      { title: 'Place it', text: 'Add it to the page and position it.' },
      { title: 'Fill content', text: 'Edit copy or generate with AI, then publish.' },
    ],
  },
  {
    id: 'publishing',
    slug: 'real-time-publishing',
    title: 'Real-Time Publishing',
    summary: 'Approved edits go live instantly — no waiting on deploys for content.',
    demo: 'publish',
    image: 'feature-publish.jpg',
    accent: '#ff695f',
    points: [
      'Ship content updates the moment they are approved',
      'Faster campaign and seasonal turnaround',
      'Fewer handoffs between content and engineering',
      'Preview before you publish with confidence',
      'Iterate without opening tickets',
      'Keep the live site fresh every day',
      'Role controls protect who can go live',
    ],
    body: 'Everyday content should not wait on a release train. Proxwebs publishes approved changes in real time so marketing can react to campaigns, news, and seasonal needs immediately.',
    highlights: [
      { title: 'Instant go-live', text: 'Approved edits appear on the site right away.' },
      { title: 'Safe iteration', text: 'Preview first, then publish with permissions.' },
      { title: 'Less waiting', text: 'No deploy cycle for routine content work.' },
    ],
    steps: [
      { title: 'Edit', text: 'Update pages, sections, or media in the admin.' },
      { title: 'Preview', text: 'Confirm the look and message.' },
      { title: 'Publish', text: 'Go live instantly with the right role.' },
    ],
  },
  {
    id: 'rbac',
    slug: 'role-based-access',
    title: 'Role-Based Access',
    summary: 'Delegate editing confidently with roles and section-level permissions.',
    demo: 'rbac',
    image: 'feature-rbac.jpg',
    accent: '#03a4ed',
    points: [
      'Control who can edit which sections',
      'Keep publishing safe for non-tech contributors',
      'Assign roles and privileges from the dashboard',
      'Reduce risk without slowing the team down',
      'Separate draft work from publish rights',
      'Support marketing, ops, and leadership workflows',
      'Audit-friendly access for growing teams',
    ],
    body: 'Speed without chaos means the right people can edit the right things. Role-based access lets you open the CMS to more contributors while protecting sensitive areas and publish controls.',
    highlights: [
      { title: 'Granular permissions', text: 'Scope access by role and section.' },
      { title: 'Safe delegation', text: 'More editors, less risk.' },
      { title: 'Clear ownership', text: 'Publishing stays intentional.' },
    ],
    steps: [
      { title: 'Define roles', text: 'Create roles that match how your team works.' },
      { title: 'Assign access', text: 'Grant section and publish privileges.' },
      { title: 'Collaborate safely', text: 'Let more people contribute with guardrails.' },
    ],
  },
  {
    id: 'dashboard',
    slug: 'admin-dashboard',
    title: 'All-in-One Admin Dashboard',
    summary: 'Pages, menus, sections, templates, contacts, users, and roles in one place.',
    demo: 'dashboard',
    image: 'feature-dashboard.jpg',
    accent: '#ff695f',
    points: [
      'Central workspace for site structure and content',
      'Manage pages, menus, sections, and templates together',
      'Contacts and leads alongside publishing tools',
      'Users, roles, and privileges in the same admin',
      'Less context-switching for busy teams',
      'Import and export for backups and migrations',
      'One login for the whole publishing stack',
    ],
    body: 'Fragmented tools slow teams down. The Proxwebs admin brings structure, design, content, contacts, and access control into a single dashboard so everyday website work stays focused.',
    highlights: [
      { title: 'Unified admin', text: 'Stop juggling disconnected systems.' },
      { title: 'Full site control', text: 'From pages to permissions in one place.' },
      { title: 'Built for teams', text: 'Marketing, ops, and leadership share one workspace.' },
    ],
    steps: [
      { title: 'Sign in', text: 'Open the all-in-one admin dashboard.' },
      { title: 'Manage', text: 'Edit pages, design, contacts, and users.' },
      { title: 'Publish', text: 'Ship updates without leaving the workspace.' },
    ],
  },
  {
    id: 'import-export',
    slug: 'import-export',
    title: 'Import & Export',
    summary: 'Move content in and out for backups, migrations, and workflows.',
    demo: 'importexport',
    image: 'feature-importexport.jpg',
    accent: '#03a4ed',
    points: [
      'Export content for backup and migration',
      'Import structured data into your workflow',
      'Reduce lock-in when moving between environments',
      'Support handoffs between teams and vendors',
      'Keep a recoverable copy of critical content',
      'Speed up staging-to-production transfers',
      'Pair with templates for faster site rebuilds',
    ],
    body: 'Your content should travel with you. Import and export tools help teams back up work, migrate between environments, and keep publishing flexible as the organization grows.',
    highlights: [
      { title: 'Backup ready', text: 'Export critical content when you need it.' },
      { title: 'Migration friendly', text: 'Move structured data between workflows.' },
      { title: 'Less lock-in', text: 'Keep ownership of your site content.' },
    ],
    steps: [
      { title: 'Choose data', text: 'Select what to export or import.' },
      { title: 'Transfer', text: 'Run the import or export from the admin.' },
      { title: 'Verify', text: 'Confirm content landed correctly, then publish.' },
    ],
  },
  {
    id: 'seo',
    slug: 'seo-ready-copy',
    title: 'SEO-Ready Publishing',
    summary: 'AI-assisted titles, taglines, and descriptions built into the workflow.',
    demo: 'seo',
    image: 'feature-seo.jpg',
    accent: '#ff695f',
    points: [
      'AI help for SEO-friendly titles and descriptions',
      'Taglines and meta-style copy in the same flow',
      'Describe → Generate → Refine → Publish path',
      'Consistent presentation with smart image fit',
      'Faster page launches without SEO afterthoughts',
      'Editable suggestions you stay in control of',
      'Better discoverability with less busywork',
    ],
    body: 'SEO should not be a separate project after the page is done. Proxwebs weaves title, tagline, and description assistance into the publishing workflow so every page launches search-ready.',
    highlights: [
      { title: 'Built-in assist', text: 'Generate SEO-minded copy while you edit.' },
      { title: 'Human final say', text: 'Refine suggestions before publishing.' },
      { title: 'Repeatable workflow', text: 'Same path from brief to live page every time.' },
    ],
    steps: [
      { title: 'Draft the page', text: 'Build the section and core message.' },
      { title: 'Generate SEO copy', text: 'Create titles and descriptions with AI help.' },
      { title: 'Refine & publish', text: 'Polish wording and go live.' },
    ],
  },
  {
    id: 'contacts',
    slug: 'contact-management',
    title: 'Contact & Lead Capture',
    summary: 'Collect inquiries in the same admin where you manage the website.',
    demo: 'contacts',
    image: 'feature-contacts.jpg',
    accent: '#03a4ed',
    points: [
      'Capture contact form submissions in the dashboard',
      'Keep leads next to the pages that generate them',
      'Respond faster with less tool switching',
      'Support demo requests and newsletter signups',
      'Give sales and marketing a shared inbox view',
      'Reduce lost inquiries from scattered mailboxes',
      'Connect publishing work to real conversations',
    ],
    body: 'Website work and lead follow-up belong together. Contact management lives in the CMS admin so teams see inquiries where they already manage pages, campaigns, and publishing.',
    highlights: [
      { title: 'In-admin inbox', text: 'Review submissions without leaving Proxwebs.' },
      { title: 'Faster response', text: 'Less hunting across email and forms tools.' },
      { title: 'Campaign aware', text: 'Connect page updates to inbound interest.' },
    ],
    steps: [
      { title: 'Publish forms', text: 'Use contact and newsletter capture on the site.' },
      { title: 'Collect', text: 'Submissions land in the admin dashboard.' },
      { title: 'Follow up', text: 'Route leads to the right teammate quickly.' },
    ],
  },
];

export function getFeatureBySlug(slug) {
  return features.find((feature) => feature.slug === slug) || null;
}

export function getRelatedFeatures(slug, limit = 3) {
  const current = getFeatureBySlug(slug);
  if (!current) return features.slice(0, limit);
  return features.filter((feature) => feature.slug !== slug).slice(0, limit);
}
