export const teamMembers = [
    {
        id: 'shahina',
        name: 'Ms. Shahina Sanoof',
        role: 'Managing Director',
        image: 'shahina-sanoof.png',
        shortBio: 'Guides company direction and ensures strategy turns into strong organizational results.',
        bio: 'As Managing Director, Ms. Shahina Sanoof leads the organization with a focus on strategic direction, governance, and sustainable growth. She works closely with leadership to align teams, strengthen operations, and keep the company moving toward clear long-term goals. Her leadership brings balance between vision, people, and performance.',
        focus: ['Strategic direction', 'Organizational leadership', 'Governance & growth'],
    },
    {
        id: 'akhila',
        name: 'Ms. Akhila S',
        role: 'General Manager',
        image: 'akhila-s.png',
        shortBio: 'Drives organizational performance and keeps teams aligned around clear business goals.',
        bio: 'As General Manager, Ms. Akhila S oversees business operations and team coordination to keep the organization running smoothly. She focuses on execution, communication, and accountability — ensuring priorities stay clear and departments work together toward shared outcomes. Her leadership helps turn strategy into consistent day-to-day results.',
        focus: ['Business operations', 'Team coordination', 'Performance management'],
    },
    {
        id: 'shiras',
        name: 'Shiras Sharaf',
        role: 'Team Lead',
        image: 'shiras-sharaf.png',
        shortBio: 'Leads the engineering team and guides delivery of reliable, high-quality product features.',
        bio: 'Shiras Sharaf is a Team Lead who guides the engineering team through planning, development, and delivery. He balances hands-on coding with clear technical direction — helping the team ship dependable features, maintain code quality, and move fast without losing focus. His leadership keeps collaboration smooth and product goals firmly on track.',
        focus: ['Team leadership', 'Full-stack development', 'Delivery & quality'],
    },
    {
        id: 'sowmiya',
        name: 'Sowmiya P',
        role: 'Software Developer',
        image: 'sowmiya-p.png',
        shortBio: 'Builds and improves CMS features with clean code and a focus on reliable user-facing experiences.',
        bio: 'Sowmiya P is a Software Developer who contributes to the Proxwebs CMS across feature development, bug fixes, and product refinements. She works closely with the engineering team to turn requirements into dependable functionality — helping keep the platform stable, intuitive, and ready for the teams who publish with it every day.',
        focus: ['Feature development', 'Code quality', 'Product delivery'],
    },
    {
        id: 'athira',
        name: 'Athira N',
        role: 'Lead - HR & ER',
        image: 'athira-n.png',
        shortBio: 'Builds a people-first culture and strengthens employee relations across the organization.',
        bio: 'Athira N leads Human Resources and Employee Relations with a focus on talent, culture, and workplace well-being. She connects organizational goals with people practices — supporting hiring, engagement, and a healthy work environment where teams can grow and perform at their best. Her approachable leadership helps keep the company aligned, supported, and ready to scale.',
        focus: ['Human resources', 'Employee relations', 'Culture & engagement'],
    },
    {
        id: 'noora',
        name: 'Noora Fathima',
        role: 'QA Specialist',
        image: 'noora-fathima.png',
        shortBio: 'Ensures every release is reliable by catching issues early and protecting product quality.',
        bio: 'Noora Fathima is a QA Specialist focused on keeping the CMS stable, polished, and ready for real users. She carefully validates features across workflows — from editing and publishing to AI-assisted content — so bugs are caught early and quality stays high. Her attention to detail helps the team ship with confidence.',
        focus: ['Quality assurance', 'Functional testing', 'Release readiness'],
    },
    {
        id: 'anaswara',
        name: 'Anaswara B M',
        role: 'QA Specialist',
        image: 'anaswara-bm.png',
        shortBio: 'Validates features end to end so every release feels smooth, stable, and user-ready.',
        bio: 'Anaswara B M is a QA Specialist who carefully checks product flows to make sure features work as expected before they go live. She focuses on usability, consistency, and catching edge cases early — helping the team deliver a CMS experience that feels dependable for every user.',
        focus: ['Manual testing', 'User flow validation', 'Bug reporting'],
    },
    {
        id: 'devika',
        name: 'Devika A',
        role: 'Creative Visual Specialist',
        image: 'devika-a.png',
        shortBio: 'Shapes visual identity and design assets that keep the product looking polished and on-brand.',
        bio: 'Devika A is a Creative Visual Specialist who brings clarity and creativity to the brand. She crafts visual assets, layouts, and design details that make the product feel cohesive and professional — from marketing creatives to interface-ready graphics. Her work helps the team present ideas with style and consistency.',
        focus: ['Brand visuals', 'Creative design', 'UI graphics'],
    },
];

export const teamIntro = {
    eyebrow: 'Our Team',
    homeTitle: 'People behind the <em>product</em>',
    homeSubtitle: 'A small team focused on one problem: making website publishing fast, safe, and AI-assisted.',
    pageTitle: 'Meet the team building the AI-native CMS',
    pageLead:
        'We are product, engineering, AI, and design specialists working on one shared goal — help teams publish great websites without waiting on developers.',
};
